### ISSUE TITLE
반갑습니다.

### ISSUE THREAD

**Issue by alexseong** [koosyong/caffestudy#12]
아직 초보 수준이지만 열심히 해 보려 합니다.
작은 기여라도 할 수 있는 기회가 주어진다면 더욱 감사하고요

**Comment by koosyong** [comment]
네. 반갑습니다. ^^ 인사는 [Issue 2: 인사합시다.](https://github.com/koosyong/caffestudy/issues/2) 에서 한꺼번에 하는게 좋을것 같아서, 거기로 글을 옮겨주시면 감사하겠습니다. 이 이슈는 닫도록 할게요~
