### ISSUE TITLE
의견: 투토리얼->튜토리얼 안되나용? ㅎㅎ

### ISSUE THREAD

**Issue by x2factor** [koosyong/caffestudy#14]
안녕하세요 Terry에용

구경왔다가 들러봅니당~ KOROS도 여기에 위키를 만들 걸 그랬네요 (이놈의 귀차니즘ㅠ)
제가 조만간 블로그에 딥러닝 공부자료 모음 글 하나 쓸텐데,
그거 다 쓰면 여기에 링크 걸게용 ^^
모두 화이팅이요~!

**Comment by koosyong** [comment]
ㅎㅎ 감사! 의견 반영했습니다. ^^ 한글로 글을 써보려니깐 띄어쓰기며 맞춤법이며 외래어 표기며 쉽지 않네요~ ㅎㅎ 영어는 더 못하고.. 이러다가 제대로 구사하는 언어가 하나도 없을것 같습니다.

**Comment by koosyong** [comment]
아, GitHub는 오픈소스가 프로젝트 중심이라 KOROS가 하기는 좀 그렇고.. 나중에 같이 프로젝트 하나 만들어바요..
