### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by DongHyunLeee** [koosyong/caffestudy#6]
Theano를 깔았지만 ㅋㅋ Caffee도 깔고 Deep Learning을 해보려고 합니다.

설치에 얼마나 많은 힘듦이 예상되나.....

갈아탈꺼면 빨리 갈아타야줘 ㅋ

잘부탁 드려요

**Comment by koosyong** [comment]
네. 반갑습니다. ^^ 죄송한데, [Issue 2: 인사합시다.](https://github.com/koosyong/caffestudy/issues/2) 로 글을 옮겨주시면 감사하겠습니다.
