### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by chuckgu** [koosyong/caffestudy#7]
대학원생이구요

caffe에 있는 모델가지고 kaggle문제 풀고

있는중입니다

많이 배웠으면 좋겟네요 ㅎ

**Comment by koosyong** [comment]
네. 반갑습니다. ^^ 죄송한데, [Issue 2: 인사합시다.](https://github.com/koosyong/caffestudy/issues/2) 로 글을 옮겨주시면 감사하겠습니다.
